### ISSUE TITLE
Ó nie da rady wpisać

### ISSUE THREAD

**Issue by MikolajBalcerek** [grzegorz2047/KCK-saper#5]
Wpisanie Ż albo Ó albo ż albo ó w chat i naciśnięcie enter wywala program
EDIT: Naprawiłem. Nie da się wpisać Ó.

**Comment by grzegorz2047** [comment]
@Krooku To błąd:
Traceback (most recent call last):
  File "C:/Users/grzeg/Documents/SAPER/Python-project/src/__main__.py", line 49, in <module>
    chat.ask(event)
  File "C:\Users\grzeg\Documents\SAPER\Python-project\src\recognize_words.py", line 94, in ask
    plik.writelines(self.current_string)
TypeError: writelines() argument must be a sequence of strings

**Comment by MikolajBalcerek** [comment]
Naprawiłem ż, ó, Ż poprzez dodanie na początku.

import sys
reload(sys)
sys.setdefaultencoding('utf8')

Ó jest niewpisane w konsoli i w pliku, konsola pokazuje krzaczki zamiast ó,ż (ale do pliku się wpisuje ok)
